### buscar todos os IDs
GET http://localhost:3000/user/

### buscar saldo  e extrato pelo ID  c
GET http://localhost:3000/user/67fada53-9386-4cb8-8065-47721005104a

### inserir user
POST http://localhost:3000/user/
content-type: application/json

{
    "name": "tiago",
    "saldo": 0,
    "transicao": []
}

### add deposito
PUT  http://localhost:3000/user/deposito/67fada53-9386-4cb8-8065-47721005104a
content-type: application/json

{
    "name": "tiago",
    "transicao": [{
      "tipo": "deposito",
      "valor": 100
    }]
}

### add retirada
PUT  http://localhost:3000/user/retirada/67fada53-9386-4cb8-8065-47721005104a
content-type: application/json

{
    "name": "tiago",
    "transicao": [{
      "tipo": "retirada",
      "valor": 100
    }]
}

### deletar user
delete http://localhost:3000/user/943de695-889f-4deb-8f60-0013347ce1a5

### Atualizar um usuario pelo ID
PUT  http://localhost:3000/user/943de695-889f-4deb-8f60-0013347ce1a5
content-type: application/json

{
    "name": "tiago",
    "saldo": 50,
    "transicao": [{}]
}

### buscar Ids pela rota USER
GET http://localhost:3000/user/
