### buscar todos os IDs
GET http://localhost:3000/user/

### buscar saldo  e extrato pelo ID
GET http://localhost:3000/user/7445407d-933f-46fb-a012-4a9a13381d8d

### inserir user
POST http://localhost:3000/user/
content-type: application/json

{
    "name": "tiago",
    "End": "xxx",
    "CEP": "xxx",
    "CPF": "xxx",
    "saldo": 0,
    "transacao": []
}

### add deposito
PUT  http://localhost:3000/user/deposito/7445407d-933f-46fb-a012-4a9a13381d8d
content-type: application/json

{
    "transacao": [{
      "tipo": "deposito",
      "valor": 100
    }]
}

### add retirada
PUT  http://localhost:3000/user/retirada/7445407d-933f-46fb-a012-4a9a13381d8d
content-type: application/json

{
    "transacao": [{
      "tipo": "retirada",
      "valor": 100
    }]
}

### deletar user
delete http://localhost:3000/user/7445407d-933f-46fb-a012-4a9a13381d8d

### Atualizar um usuario pelo ID
PUT  http://localhost:3000/user/7445407d-933f-46fb-a012-4a9a13381d8d
content-type: application/json

{
    "name": "matheus",
    "End": "xxx",
    "CEP": "xxx",
    "CPF": "xxx",
    "saldo": 0,
    "transacao" []
}

### buscar Ids pela rota USER
GET http://localhost:3000/user/
